#!/usr/bin/env node
import { render, sizes, sources } from "../render.js";

async function generate() {
  let sourceArg = process.argv[2];
  let sizeArg = process.argv[3];

  if (sourceArg == "all") {
    for (const source of Object.keys(sources)) {
      await render(source, sizeArg);
    }
  } else if (sizeArg == "all") {
    for (const size of Object.keys(sizes)) {
      await render(sourceArg, size);
    }
  } else {
    await render(sourceArg, sizeArg);
  }
}

generate();
